version: "3.9"

services:
  ducksoup:
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia
              count: all
  experiment:
    build:
      context: ../examples/otree