version: "3.9"

services:
  ducksoup:
    build:
      context: git@github.com:ducksouplab/ducksoup#container
      dockerfile: docker/Dockerfile.build.multi
      args:
        - appuser=$DOCKER_USER
        - appgroup=$DOCKER_GROUP